### ISSUE TITLE
Text not appearing in BigButton 

### ISSUE THREAD

**Issue by gledis69** [BalajSaleem/Foodster-Flutter#1]
Not sure if it is a phone / particular OS thing, I am running on a Xiaomi Note 7
![screenshot](https://user-images.githubusercontent.com/43916939/103777456-f3e68800-5041-11eb-8576-dd921c226b1d.jpeg)

**Comment by PermanAtayev** [comment]
@gledis69 can you check out the application from development_perman branch and see if the text is there now?

**Comment by PermanAtayev** [comment]
if the issue is still there you can reopen it here. @gledis69
